### ISSUE TITLE
Release for Scala 2.11

### ISSUE THREAD

**Issue by utdemir** [yannick-cw/http4s-prometheus#1]
Hi,

Thanks for this library. If possible, can I ask you to publish it also for Scala 2.11? I'm stuck with using that version because of Apache Spark and it'll be cool if I can just use this library without too much hassle.

**Comment by yannick-cw** [comment]
I think there is 
https://github.com/http4s/http4s/tree/master/prometheus-server-metrics/src/main/scala/org/http4s/server/prometheus
prometheus integration in http4s itself now, did you check that?

**Comment by utdemir** [comment]
I didn't know that, and that works for me, thank you very much!

Maybe it'll be useful for the future if you put that link to README.md?

Thanks again.
